language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: IUuVv4k4tjw1TJn+KQZUAI5jWotSxJ2WSeFOPgidULQa+EdSAcryAQpOP1OqOETRT8KGkyN7ciM8Ca5ze3/hZny2no6FbIbJ6vlRWfOk5O8o5gnVuUgONX4gOwmc1av7PCYuEWDubpkcGLbSqSuzCbUJhkUUwt3hoqH2JCtUc/08fNcHXjQHsEkIiYAT7WiK4o4+3vtaK2AawLQzUmKnNZN4S2U3t6WTuf5fZArtidY8GvB+3f2wGGaH13XzehoNzSHnmjZzPjsUfEjaKvzrFh4I7xR+fvO8CQJ706Vp7tgX+FmpRiENvVPVVN9EFKRvuq6XzwD0wmVM4nnU8ef41G+KT/tNHDDkM7Y1wgISOzHy/zA/+VsF7Td/ssjlPnLv9SZvrrzn7UkTSRumve1/ViIs0umNNbmCgbDWrLfJOoCss11LPBFrDoNOThzZILXq2mW4ODwsIeN03DHiqWNBi1pvARHvyRinmfujAQM7CgneuzmEiry9R2oc2SksnfoRXxvqjQd1ApBHJYwO3jQiqBgovr7oX3Nq6Yh7OanBSeCMWhnD+/nCuuiEhQgMvZu/A4SEfpZYjwbLgwrFGDSoqNHBe3qY+Qf82298VwHNAFfcEC3GC136uKNAw4HDuh2BI1d8inwQRMGvPdN5lHZilyxMmVVQ0J+TWYkrpt1/DHg=
